### PR TITLE
Set custom priority to metadata instead of fixed `default`

### PR DESCRIPTION
**Pull request by shsamkit**
I see [taskhawk-terraform-generator](https://github.com/Standard-Cognition/taskhawk-terraform-generator/blob/a9f9b86c1cbfb36f7abc6b0f365b61f34af20f0d/templates/google/apps.tf.tmpl#L61) supports `priority` in scheduler jobs but this module still hardcodes it to `default`

### CODE REVIEW

**Review by maroux — CHANGES_REQUESTED** [review]
Priority is already available in every module invocation since we have 4 specific queues. Just add an internal variable for priority in the queue module variables (rather than scheduler jobs).

**Comment by shsamkit** [comment]
> Priority is already available in every module invocation since we have 4 specific queues. Just add an internal variable for priority in the queue module variables (rather than scheduler jobs).

Sure, makes sense. I assumed we would want to forwards the configuration in generated `apps.tf` but I realize that variable is just for clasifying the scheduler-jobs.

**Comment by shsamkit** [comment]
@maroux , after review I will need your help publishing the releases on `git` and on `terraform repo`. If you can give me temporary access to releases, I won't have to bother you on your leave ~ or I can push back the release for this fix, eitherway

**Review by maroux — APPROVED** [review]

**Comment by maroux** [comment]
> @maroux , after review I will need your help publishing the releases on `git` and on `terraform repo`. If you can give me temporary access to releases, I won't have to bother you on your leave ~ or I can push back the release for this fix, eitherway 
> 
> 

You should have permissions already..

**Comment by shsamkit** [comment]
I could push a tag here but I don't see the `Resync module` option on [the registry](https://registry.terraform.io/modules/standard-ai/taskhawk-queue/google/latest)

**Pull request merged**
